### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by Geczy** [noammanyfler/otorio-components#1]
Any chance you'd update to webpack 5 and antd 4 and @babel etc?

**Comment by noammanyfler** [comment]
Hi Geczy, hope you're doing well. 
I recently moved from my job as a Full Stack developer to BigData developer, therefore I'm no longer active in the React/Webpack ecosystem.
From what I remember there are breaking changes in Webpack 5 and antd 4, but unfortunately I don't plan on updating this guide. If something changes I'll update here.
